sudo: false
language: php

php:
  - 7.3
  - 7.2
  - 7.1

env:
  - FLOW_VERSION=5.3
  - FLOW_VERSION=5.2
  - FLOW_VERSION=5.1
  - FLOW_VERSION=5.0
  - FLOW_VERSION=4.3

before_script:
  - git clone https://github.com/neos/flow-development-distribution.git -b ${FLOW_VERSION} ../flow
  - cd ../flow
  - composer self-update
  - bash ../aimeos-flow/.travis.sh

script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml --coverage-clover Packages/Application/Aimeos.Shop/coverage-unit.xml --whitelist Packages/Application/Aimeos.Shop/Classes Packages/Application/Aimeos.Shop/Tests/Unit/
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --coverage-clover Packages/Application/Aimeos.Shop/coverage-functional.xml --whitelist Packages/Application/Aimeos.Shop/Classes Packages/Application/Aimeos.Shop/Tests/Functional/

after_success:
  - php bin/coveralls -c Application/Aimeos.Shop/.coveralls.yml

matrix:
  fast_finish: true
  exclude:
  - php: 7.3
    env: FLOW_VERSION=4.3
  include:
  - php: 7.0
    env: FLOW_VERSION=4.3
