sudo: false
language: php

php:
  - 7.0
  - 7.1

before_script:
  - git clone https://github.com/neos/flow-development-distribution.git -b 4.0 ../flow
  - cd ../flow
  - composer self-update
  - bash ../aimeos-flow/.travis.sh

script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml --coverage-clover Packages/Application/Aimeos.Shop/coverage-unit.xml --whitelist Packages/Application/Aimeos.Shop/Classes Packages/Application/Aimeos.Shop/Tests/Unit/
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --coverage-clover Packages/Application/Aimeos.Shop/coverage-functional.xml --whitelist Packages/Application/Aimeos.Shop/Classes Packages/Application/Aimeos.Shop/Tests/Functional/

after_success:
  - php bin/coveralls -c Application/Aimeos.Shop/.coveralls.yml