sudo: false
language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
  - bash -c .travis.sh

script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Aimeos.Shop/Tests/Unit/
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Aimeos.Shop/Tests/Functional/

after_success:
#  - php vendor/bin/coveralls