sudo: false
language: php

php:
  - 7.0
  - 5.6
  - 5.5

before_script:
  - git clone https://github.com/neos/flow-development-distribution.git -b 3.3 ../flow
  - cd ../flow
  - composer self-update
  - bash ../aimeos-flow/.travis.sh

script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml --coverage-clover coverage-unit.xml --whitelist Classes Packages/Application/Aimeos.Shop/Tests/Unit/
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml --coverage-clover coverage-functional.xml --whitelist Classes Packages/Application/Aimeos.Shop/Tests/Functional/

after_success:
  - php vendor/bin/coveralls