-
  name: 'Admin index page'
  uriPattern: 'admin'
  defaults:
    '@package':    'Aimeos.Shop'
    '@controller': 'Admin'
    '@action': 'index'
    '@format': 'html'
  appendExceedingArguments: true

-
  name: 'Jqadm'
  uriPattern: 'admin/{site}/jqadm<JqadmSubroutes>'
  subRoutes:
    'JqadmSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Jqadm'

-
  name: 'Jsonadm'
  uriPattern: 'admin/{site}/jsonadm<JsonadmSubroutes>'
  subRoutes:
    'JsonadmSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Jsonadm'

-
  name: 'Jsonapi'
  uriPattern: 'jsonapi<JsonapiSubroutes>'
  subRoutes:
    'JsonapiSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Jsonapi'

-
  name: 'Account'
  uriPattern: 'myaccount<AccountSubroutes>'
  subRoutes:
    'AccountSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Account'

-
  name: 'Default'
  uriPattern: '<DefaultSubroutes>'
  subRoutes:
    'DefaultSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Default'

-
  name: 'Update'
  uriPattern: '<UpdateSubroutes>'
  subRoutes:
    'UpdateSubroutes':
      package: 'Aimeos.Shop'
      suffix:  'Update'


-
  name: 'Example terms and conditions page'
  uriPattern: 'terms'
  defaults:
    '@package':    'Aimeos.Shop'
    '@controller': 'Page'
    '@action': 'terms'
    '@format': 'html'
  appendExceedingArguments: true

-
  name: 'Example privacy policy page'
  uriPattern: 'privacy'
  defaults:
    '@package':    'Aimeos.Shop'
    '@controller': 'Page'
    '@action': 'privacy'
    '@format': 'html'
  appendExceedingArguments: true
